const mockData = [
  {
    firstName: "alain",
    lastName: "larose",
    startDate: "01/02/2000",
    department: "Sales",
    dateOfBirth: "06/21/1968",
    street: "Fernand Herbaut",
    city: "Aulnay",
    state: "AL",
    zipCode: "93600",
  },
  {
    firstName: "louis",
    lastName: "delaporte",
    startDate: "07/06/2004",
    department: "Human Resources",
    dateOfBirth: "10/07/1970",
    street: "Victor Hugo",
    city: "Bondy",
    state: "AK",
    zipCode: "93200",
  },
  {
    firstName: "Stéphanie",
    lastName: "lecourbe",
    startDate: "09/12/2014",
    department: "Marketing",
    dateOfBirth: "05/23/1990",
    street: "de la gare",
    city: "Saint Denis",
    state: "IA",
    zipCode: "93800",
  },
  {
    firstName: "Roger",
    lastName: "lebon",
    startDate: "03/16/1999",
    department: "Engineering",
    dateOfBirth: "08/14/1980",
    street: "Gaston Leroux",
    city: "Paris",
    state: "CO",
    zipCode: "75000",
  },
  {
    firstName: "christine",
    lastName: "toutin",
    startDate: "11/18/2020",
    department: "Legal",
    dateOfBirth: "02/23/1984",
    street: "blanche",
    city: "paris",
    state: "CO",
    zipCode: "75000",
  },
  {
    firstName: "warda",
    lastName: "ichir",
    startDate: "08/03/2001",
    department: "Human Resources",
    dateOfBirth: "04/14/1980",
    street: "Anatole France",
    city: "Livry Gargan",
    state: "VI",
    zipCode: "93000",
  },
  {
    firstName: "Jessica",
    lastName: "cado",
    startDate: "05/09/2002",
    department: "Sales",
    dateOfBirth: "02/15/1966",
    street: "froide",
    city: "caen",
    state: "MD",
    zipCode: "14000",
  },
  {
    firstName: "frédéric",
    lastName: "lausin",
    startDate: "02/13/2018",
    department: "Engineering",
    dateOfBirth: "12/11/1991",
    street: "basse",
    city: "rouen",
    state: "AS",
    zipCode: "76000",
  },
  {
    firstName: "laurence",
    lastName: "portal",
    startDate: "09/29/2003",
    department: "Engineering",
    dateOfBirth: "08/27/1994",
    street: "point du jour",
    city: "nantes",
    state: "KS",
    zipCode: "44000",
  },
  {
    firstName: "thierry",
    lastName: "lafronde",
    startDate: "05/24/1996",
    department: "Sales",
    dateOfBirth: "04/01/1969",
    street: "haute",
    city: "Montreuil",
    state: "IL",
    zipCode: "93000",
  },
  {
    firstName: "Victoria",
    lastName: "Victor",
    startDate: "11/07/2000",
    department: "Sales",
    dateOfBirth: "10/27/1976",
    street: "de la victoire",
    city: "Rouen",
    state: "KY",
    zipCode: "76000",
  },
  {
    firstName: "Estelle",
    lastName: "Rebelle",
    startDate: "24/02/1999",
    department: "Legal",
    dateOfBirth: "30/01/1967",
    street: "transversale",
    city: "Clermont-Ferrand",
    state: "CF",
    zipCode: "63000",
  },
];

export default mockData;
